language: node_js
cache: npm
node_js:
- '8'
matrix:
  include:
  - os: osx
    install:
    - npm i
    script:
    - cd native/electron
    - npm run build
    - npm run package:mac
    - cd ../..
  - os: windows
    install:
    - npm i
    script:
    - cd native/electron
    - npm run build
    - npm run package:windows
    - cd ../..
deploy:
  provider: releases
  api_key:
    secure: qq/G5CODn+W5EBVDwcr2tGhq6ESiRMNxk8P7sucfAfg3FZS8MZDy5x6TtlsdEgPxn3nI9/4Sv9lTvGJ/VqFFKt+n9zOF3DTY+lF3izcICzHy3u6vCkNGOovtyGyd8haCguFhVLXggvaKWzv8ifpvk5xCNw7BAQfXWRxUon8xpdgLpHBlO3WDwxG6l26l//4ZeH0cDU4/xfepXBlhMoObfJGa7Iho/YoCkC2fMowIQ4OevEq4i+YFFea4MRM/jzIARBlhCMhSGBpAI2jcepEYpCN20jK7fp9kOrmnOW/Xo2tkv9f1AvJPlYnLm+IUTSX4BZyyN1DkYsh7wgFq70PwOEH3s3zskZMHKiIhnOHtYuUj+Meh0D0gGDMuSGRV4P1caIm6nE7N3MHXodlY9+QE6FPjS2aRSu1IRY0rz4KRNmet6iICF8fhLVvqmA7k4+j67W6IBAS4YT6x7Yk1BhgadSOxt473w+ybYrm4nqesIod69DHxf/YQvRT2PzPh++Pk/qir8J7dK+PrtouIjjLomFnZZO3N+FVYCR4VCgHRSyeCrk8LxvwQ+7DhHXrpku6qdSwe8e8+bzBr36eSc4SS8amrzrnO5jq1jhM/RYoN9h2tPgbCm2Q9PAEs53OfYaz31ZNrTh1yEbfyiu/amaYZbOh5/jq1Imy0h7+v1lFwY=
  file_glob: true
  skip_cleanup: true
  file: native/electron/packaged/*
  on:
    repo: langyo/MCBBS-Client
    branch: master
    tags: true
